# Yaml file for configuration
# Replace each value with yours
# Set daily to True if you want your file to be daily
# Note that Raspberry needs to log to internet to retrieve current hour
---
service: 
  daily: False

parameters: 
  file_name: gnss_r
  path_to_file: /home/user
  port: 9600

